### PR TITLE
Prep for CRAN

### PR DESCRIPTION
**Pull request by bpbond**
* Added NEWS file - common for R packages
* Added `quiet = TRUE` to several of the `pdr_optimize` calls in the vignette

Questions:
* Are we happy staying with version 0.1?
* Remove the package startup message?

### CODE REVIEW

**Comment by bpbond** [comment]
Let's discuss when we meet?

**Comment by bpbond** [comment]
https://cran.r-project.org/web/packages/policies.html

**Review by kendalynnm — APPROVED** [review]
Changed the version to 1.0.0 in the "News".

Also, super minor, but the test value for ap_prec is not consistent across functions. Not sure if it's worth changing?

**Comment by bpbond** [comment]
>not consistent

I don't know if it's worth it or not. If you noticed it, and it might cause confusion, then perhaps yes?

**Comment by bpbond** [comment]
>Changed the version to 1.0.0 in the "News".

Thanks for catching that!

**Comment by kendalynnm** [comment]
> > not consistent
> 
> I don't know if it's worth it or not. If you noticed it, and it might cause confusion, then perhaps yes?

fixed now, see https://github.com/COMPASS-DOE/PoolDilutionR/commit/37b13a3bdfd3a53102eb7287a22179e3cdb1518c

**Pull request merged**
